config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :feelings, only: [:index, :new, :create]

  resources :users, only: [:show, :update], param: :username

  resources :comments, only: [:create]

  resources :likes, only:[:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feeling.rb
# frozen_string_literal: true

class Feeling < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  DETAILS = [ 'drink', 'music', 'wifi_password', 'coffee_shop']
  DETAILS.each do |detail|
    define_method "#{detail}_html" do
      case detail
      when "drink"
        "<i class='fas fa-mug-hot'></i>  #{self.drink}" unless self.drink&.empty?
      when "music"
        "<i class='fas fa-music'></i>  #{self.music}" unless self.music&.empty?
      when "coffee_shop"
        "<i class='fas fa-store-alt'></i>  #{self.coffee_shop}" unless self.coffee_shop&.empty?
      when "wifi_password"
        "<i class='fas fa-wifi'></i>  #{self.wifi_password}" unless self.wifi_password&.empty?
      end
    end
  end

end

app/controllers/feelings_controller.rb
# frozen_string_literal: true

class FeelingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @feelings = Feeling.all
    @comment = Comment.new
  end

  def new
    @feeling = Feeling.new
  end

  def create
    @feeling = Feeling.new(feeling_params)
    @feeling.user = current_user
    if @feeling.save
      redirect_to feelings_path
    else
      redirect_to feelings_path
      #TODO: puts error message
    end
  end

  private

  def feeling_params
    params.require(:feeling).permit(:mood, :wifi_password, :coffee_shop, :music, :drink, :date)
  end

end

app/views/shared/feelings/_card.html.slim
- feeling_arr = [feeling.drink_html, feeling.music_html, feeling.coffee_shop_html, feeling.wifi_password_html].compact
- count = feeling_arr.count
.card-container
  .left-full
    h2.vertical-text= "@" + feeling.user.username
    .item-bottom
      = display_time(feeling.created_at)
  .right-top
    p= "\"#{feeling.mood}\""
    - if feeling.date.present?
      .date= "-#{feeling.date}"
  .right-bottom
    - feeling_arr.each do |e|
      .card-detail
        = e.html_safe
  .shadow
  .like-item id="#{feeling.id}-feeling"
    = render "././likes/like_button", feeling: feeling

.comment-form-box
  .comment-line
  = form_for comment, url: comments_path, html: { method: :post } do |f|
    = f.text_field :content, placeholder: "Comment...", class: "comment-bubble-dashed", default: nil
    = f.hidden_field :feeling_id, value: feeling.id
    = f.submit "post", class: "comment-button"
.comments-container
  .comment-line-solid
  - feeling.comments.each do |comment|
    .comment-unit
      .comment-row
        .comment-author= comment.user.username
        .comment-date= display_time(comment.created_at)
      .comment-content= comment.content