config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :feelings, only: [:index, :new, :create]

  resources :users, only: [:show, :update], param: :username

  resources :comments, only: [:create]

  resources :likes, only:[:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :feeling
  belongs_to :user

  def self.likes_uid_arr
    # grouped by feeling
    result = {}
    Like.pluck(:feeling_id, :user_id).each do |arr|
      f_id = arr[0]
      u_id = arr[1]
      if result[f_id].nil?
        result[f_id] = [u_id]
      else
        result[f_id] << u_id
      end
    end
    return result
  end

  # find user_id and feeling_id
  # check if feeling_id includes the feeling
  # if not render
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    # byebug
    feeling_id = params[:feeling_id]
    @like = Like.new(feeling_id: feeling_id, user_id: current_user.id)
    respond_to do |format|
      if @like.save
        @feeling = Feeling.find(feeling_id)
        format.js { render 'likes/like.js.erb', feeling: @feeling }
      else
        byebug
      end
    end
  end

  def destroy
    like = Like.find(params[:id])
    @feeling = Feeling.find(like.feeling_id)
    respond_to do |format|
      if like.destroy
        format.js { render 'likes/like.js.erb', feeling: @feeling }
      end
   end
  end

end

app/views/likes/_like_button.html.slim
- like = Like.where(user_id: current_user.id, feeling_id: feeling.id).first
- like_num = feeling.likes.count
- like_num = like_num > 0 ? like_num : nil
- if like.nil?
  = link_to likes_path(feeling_id: feeling.id), method: :post, remote: true do
    i.far.fa-heart
- else
  = link_to like_path(like), method: :delete, remote: true do
    i.fas.fa-heart
- if like_num
  .text-small= "#{pluralize(like_num, "like")}"

app/views/likes/like.js.erb
var heart = document.getElementById(<%= @feeling.id %> + "-feeling");
var link = '<%= j render "like_button", feeling: @feeling %>';

heart.innerHTML = link;